# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0858a266f58f827ed434295ce5a634b0"
name = "Bundle App"
handle = "bundle-app-141"
application_url = "https://zoom-annotation-strand-lemon.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "bundling-app-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://zoom-annotation-strand-lemon.trycloudflare.com/auth/callback",
  "https://zoom-annotation-strand-lemon.trycloudflare.com/auth/shopify/callback",
  "https://zoom-annotation-strand-lemon.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
